#let titleEnglish = "TODO"
#let titleFrench = "TODO"
#let degree = "Master"
#let program = "Computer Science"
#let specialization = "Computer Science Theory"
#let school = "School of Computer and Communication Sciences"
#let examiner = "TODO"
#let supervisors = ("Aurèle Barrière", "Clément Pit-Claudel")
#let author = "Marcin Wojnarowski"
#let startDate = datetime(day: 22, month: 9, year: 2025)
#let submissionDate = datetime(day: 23, month: 1, year: 2026)
